### ISSUE TITLE
Update in language specific indexes?

### ISSUE THREAD

**Issue by bee-keeper** [sbaechler/django-multilingual-search#2]
Hi,

I was wondering what your opinion is about indexing content - why is it that update and remove target all indexes but only search is routed to the active language?  Maybe i've misunderstood, but don't you need to index your content in language specific indexes before this could be useful?

**Comment by sbaechler** [comment]
That's what it does. 
This graphic should explain it. For the module to work you need to have multilingual models that transparently output the correct language. 
Use a library such as [Django Modeltranslation](https://github.com/deschler/django-modeltranslation).

![index-creation](https://cloud.githubusercontent.com/assets/288516/9564041/6576d99e-4e99-11e5-9387-0bd81dac3f83.png)

**Comment by bee-keeper** [comment]
Right, that makes sense now.  I gave it a quick test drive with [django-parler](https://github.com/edoburu/django-parler) but for some reason my content in all indexes was indexed in English only (using Haystack rebuild_index management command).  I'm going to take another look and see why, perhaps there is some issue with django-parler and the context manager in the update method?

In terms of debugging index creation i guess the update() method is the place to look right?

**Comment by sbaechler** [comment]
Yes, update() is where the documents are added to the index. There is log.debug statement in there as well, so if you have a 'haystack' logger with DEBUG level, you should see the debug output.

**Comment by bee-keeper** [comment]
Hi, so I did manage to get this working with the following dirty hack.  

    with translation.override(language):
        iterable = iterable.language(language).all()
        super(ElasticsearchMultilingualSearchBackend, self).update(index, iterable, commit)

At this stage am not really sure why this should be required as testing in the shell I change the default language and django-parler returns the correct language specific results.  I suspect the issue here isn't this package so feel free to close.

**Comment by sbaechler** [comment]
This is strange. The multilingual backend is already iterating through all languages. I might add a test case for Django-parler since this is a very common module.
Thank you for reporting this.

**Comment by sbaechler** [comment]
Django-parler keeps its own language state in the models and doesn't use the Django environment. So translation.override() does nothing.

I added a compatibility fix to the master branch. It works similar to yours. Instead of re-triggering the queryset and recreating all model instances it just updates the language field on them.

**Comment by bee-keeper** [comment]
Thanks for this, Pypi release as well - win!  It's not nice having app specific code in there but I can't see another way.  When I get chance I'll test against django-hvad as well and that's all major language apps covered.

**Comment by sbaechler** [comment]
I'll release it on pypi in a few days. I like to test it in production first.
